### ISSUE TITLE
Does your youtube video not have sound intentionally, or what?

### ISSUE THREAD

**Issue by ghost** [outercloudstudio/Ike-And-Liams-s-Game#7]

**Comment by ghost** [comment]
cuz i will like it better if it had sound...

**Comment by outercloudstudio** [comment]
oh sorry

**Comment by ghost** [comment]
Plus, I know how to use a module, but what are you going to do with one that says "hoi" and I don't even know about the other one...

**Comment by outercloudstudio** [comment]
Basically:
Only You will work on Game.py
I will work on the src.py

TO MAKE A CHANGE
-do change
-commit
-push to origin

TO UPDATE THE FILES
-refresh origin
-pull from origin

To use functions form src.py just in the game .py do    src.FUNCTION
I will create functions for creating random numbers and stuff to make it easier.

**Comment by ghost** [comment]
what does src.py do?
