### ISSUE TITLE
Seed

### ISSUE THREAD

**Issue by ghost** [outercloudstudio/Ike-And-Liams-s-Game#8]
I seriously hate to ask, but what is a seed?

**Comment by ghost** [comment]
Will you censored answer me?

**Comment by outercloudstudio** [comment]
What happens is random numbers are selected based on whats called a "seed" For example the seed, 1  will always generate 5 ,19 ,8 ,34 ,1. Seed 2 will be different but if you use seed 1 again it will still do  5 ,19 ,8 ,34 ,1.

**Comment by ghost** [comment]
cool, thanks
